services:
    DigitaleDinge\ContaoKiss\Migration\Version100\ArticleContentKissStylesMigration:
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }

    DigitaleDinge\ContaoKiss\Migration\Version100\ArticleContentBackgroundColorKissStylesMigration:
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }

    DigitaleDinge\ContaoKiss\Migration\Version100\ArticleContentWidthKissStylesMigration:
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }

    DigitaleDinge\ContaoKiss\Migration\Version100\ContentMediaTypeRsceDataMigration:
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }
