services:
    DigitaleDinge\ContaoKiss\Migration\ArticleContentKissStylesMigration:
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }

    DigitaleDinge\ContaoKiss\Migration\AccentToTertiaryMigration:
        arguments:
            - '@database_connection'
        tags:
            - { name: contao.migration, priority: 0 }
