services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    DigitaleDinge\ContaoKiss\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Event,Model,Util,Styles,DigitaleDingeKissBundle.php}'

    DigitaleDinge\ContaoKiss\Styles\:
        resource: '../src/Styles/{StyleOptionRegistry.php,Option/**/*Option.php}'

    #kiss.twig.global.styles_variable:
        #class: DigitaleDinge\ContaoKiss\Twig\Global\StylesVariable
        #public: true
        #arguments:
            #- '@event_dispatcher'
            #- '%contao_kiss.style_definition_override%'

    kiss.rsce_config.builder:
        class: DigitaleDinge\ContaoKiss\CustomElementsConfigurationBuilder
        public: true

    DigitaleDinge\ContaoKiss\CustomElementsConfigurationBuilder: '@kiss.rsce_config.builder'

    kiss.asset.manifest_version_strategy:
        class: Symfony\Component\Asset\VersionStrategy\JsonManifestVersionStrategy
        arguments:
            - '%kernel.project_dir%/public/layout/manifest.json'

    DigitaleDinge\ContaoKiss\Asset\VersionStrategy\ViteVersionStrategy:
        arguments:
            $manifestStrategy: '@kiss.asset.manifest_version_strategy'
