services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    DigitaleDinge\ContaoKiss\:
        resource: '../src/'
        exclude: '../src/{Event,Model,Util,Styles,DigitaleDingeKissBundle.php}'

    #kiss.twig.global.styles_variable:
        #class: DigitaleDinge\ContaoKiss\Twig\Global\StylesVariable
        #public: true
        #arguments:
            #- '@event_dispatcher'
            #- '%contao_kiss.style_definition_override%'

    kiss.rsce_config.builder:
        class: DigitaleDinge\ContaoKiss\CustomElementsConfigurationBuilder
        public: true
        arguments:
            - '@translator'

    DigitaleDinge\ContaoKiss\CustomElementsConfigurationBuilder: '@kiss.rsce_config.builder'
